openapi: 3.0.1
info:
  title: Sport registry server API Documentation
  version: 0.0.1

paths:
  /sports/list:

  /sports/add:

  /teams/list:

  /teams/add:

  /sportsmen/list:

  /sportsmen/add:

  /competitions/list:

  /competitions/add: